### ISSUE TITLE
Raspberry Pi and communication with Flexi-HAL

### ISSUE THREAD

**Issue by drpixel8** [Expatria-Technologies/Flexi-HAL#10]
If I am understanding the README correctly, I should be able to run cnc.js on a Raspberry Pi that is attached to the GPIO header and communicate with Flexi-HAL. Is this accurate?

After following the installation guide listed on the [cnc.js website](https://cnc.js.org/docs/rpi-setup-guide/) and after enabling the serial port using `sudo raspi-config`, I am able to see an available port when running cnc.js, however, when I connect to it, I see no output when issuing GRBL commands.

I've tried searching, but have found nothing that states what pins the Flexi-HAL uses to communicate with the Raspberry Pi.  I am assuming it uses GPIO14 & GPIO15, which would correlate to UART1 on the Raspberry Pi, correct?  If not, what UART/pins should I be using.  Does Flexi-HAL expect RTS/CTS flow control or any other settings?  I've tried several combinations, but nothing seems to be working out.

What driver should I be using with this?  Does a driver with Ethernet and/or SD alter the ability to communicate with the Raspberry Pi?

**Comment by andrewmarles** [comment]
The schematic shows what pins connect where:
https://github.com/Expatria-Technologies/Flexi-HAL/blob/main/FLEXI_HAL_2000_Schematic_A5_FULL_PLACE.PDF

None of the pre-compiled builds have the UART enabled.  The builds for uFlexiNET repurpose one of the UART pins for an additional CS pin.  I would suggest just using a short jumper cable between your PI and the USB port.  Native USB-CDC is a faster and more robust communications interface than UART.
