### ISSUE TITLE
How to reset onboard settings.

### ISSUE THREAD

**Issue by hambudi** [Expatria-Technologies/Flexi-HAL#5]
I started using FlexiHal board to CNC my sherline mill. For some reason my X axis stopped moving yesterday while I was testing things (upgrading firmware etc). The issue seems to be with the board/firmware, because if I switch X with Y it works fine.

How do I reset the board to default firmware and settings?

**Comment by andrewmarles** [comment]
`$RST=$` is the command to reset the GRBL settings.  

This is the release that is currently shipping on the boards:   
https://github.com/Expatria-Technologies/STM32F4xx/releases/tag/flexi-hal-v0.9.9.8

**Comment by hambudi** [comment]
ok, I tried flashing the 9.9.8 firmware, I tried resetting the board. Looks like somehow my x axis is broken on this board. 

For now I am able to use the beta firmware with the ganged X axis to get my machine to work (By hooking up the X stepper to A). Hooking up a scope to the x axis output shows that its not outputting anything.

Any hints about how this could have happened? My board is connected to a bunch of CL-57T Closed Loop drivers running my CNC. The board is powered by a 20v laptop power adapter, and the usb cable for 5v.

**Comment by andrewmarles** [comment]
ESD is always a risk with any electronics.  There are protection devices on the board but there are not 100% proof against damage from handling.

**Comment by hambudi** [comment]
Photos below.

Black box has an unregulated 50V power supply powering the stepper drivers. Flexi was screwed to 3d printed DIN Bracket and sticky taped to the top of black box.

Only wires from flexi to black box are stepper wires, limit wires go using ethernet cable directly to the CNC. 

Flexi has USB and 20V DC connected as well.

Photos below show jog controller connected, this was not connected when the issue started happening.



![IMG_1786](https://github.com/Expatria-Technologies/Flexi-HAL/assets/2451823/8fc68a72-628e-44a5-9b1f-e531d5db5851)
![IMG_1784](https://github.com/Expatria-Technologies/Flexi-HAL/assets/2451823/a3af69b2-65be-4f72-821e-18a20696a824)
![IMG_1785](https://github.com/Expatria-Technologies/Flexi-HAL/assets/2451823/5a69cf46-f657-4279-bac4-675f3ba5abf2)

**Comment by andrewmarles** [comment]
You may want to check the grounding on the stepper drivers to ensure that there is no ground loop between your 50V supply and where the PCB external gnd is connected.  There's really no definitive answer I can give you from over here, but yoru wiring looks in the pictures.  In terms of specific failure point, as your Y axis is working the likely victim here is U17, the x-axis step/dir isolator which is at the edge of the board near the RPI header and stepper connector.

**Comment by hambudi** [comment]
In the attached photo that little chip does look pretty mangled.

![IMG_1793](https://github.com/Expatria-Technologies/Flexi-HAL/assets/2451823/e0c6f133-ac12-44f3-b65d-c0758308dc9a)

I dont understand ground loops very well, but everything in the 50V line is grounded correctly based on all the info I could find based on stepper driver wiring documentation. The only ground connection between the board and the 50V line is probably through the power strip they share, and then through the computer, through the USB port.

When I hooked up a scope to the board to see how the stepper outputs were, there was a lot of noise/ripple when not operating steppers. It cleaned up when i ran the axis. Is this indication of a ground loop?

Should I be grounding the CNC board to the stepper 50V supply more directly to avoid loops?

**Comment by hambudi** [comment]
Thanks
