### ISSUE TITLE
Using a controller with a burnt out X axis opto.

### ISSUE THREAD

**Issue by hambudi** [Expatria-Technologies/Flexi-HAL#7]
Hi, in a previous issue we determined that my board's X axis opto isolator was blown. I have been attempting to use this board using ganged x ganged y firmware. And plugging in the X axis stepper into M3.

I have a rather weird issue with this setup where if I configure my X to job correctly from the computer, the Jog2K pendant moves it in the opposite direction. I never had this issue before I used the ganged firmware.

1- I'm wondering if its possible for you to provide me a firmware where the X axis is configured to output on the M3 slot without any ganging.

2 I'd like to replace the blown opto but dont know what the part is to replace it with. Can you please link me the part number of specs so I can find an equivalent?

**Comment by hambudi** [comment]
This is the blown opto in question https://github.com/Expatria-Technologies/Flexi-HAL/issues/5#issuecomment-2076066670

**Comment by andrewmarles** [comment]
This is the part on the board:
https://www.lcsc.com/product-detail/Digital-Isolators_Corebai-Microelectronics-CBMuD1200LAS8_C476470.html

This is an equivalent from digikey:
https://www.digikey.ca/en/products/detail/analog-devices-inc/ADUM1200ARZ-RL7/995653

The source tree is here (linked from the readme) for the driver is here:
https://github.com/Expatria-Technologies/STM32F4xx

You just need to clone it and change the flexi_hal_map.h file for your desired pinout:
https://github.com/Expatria-Technologies/STM32F4xx/blob/F446_Flexi_HAL/boards/flexi_hal_map.h

**Comment by hambudi** [comment]
Thank you!
